export const creditBureau = {
  Nombre: {
    RFC: "BEGE940707XXX",
    Sexo: "M",
    Residencia: "3",
    EstadoCivil: "S",
    Nacionalidad: "MX",
    PrimerNombre: "EDUARDO",
    ApellidoMaterno: "GASPAR",
    ApellidoPaterno: "BENITEZ",
    FechaNacimiento: "07071994",
    NumeroDependientes: "01",
    ClaveImpuestosOtroPais: "BEGE940707HHGNSD17"
  },
  Cuentas: {
    Cuenta: [
      {
        MontoPagar: "0",
        TipoCuenta: "I",
        NumeroPagos: "2",
        SaldoActual: "0+",
        FechaReporte: "20072022",
        SaldoVencido: "0",
        TipoContrato: "PL",
        CreditoMaximo: "749",
        LimiteCredito: "0",
        HistoricoPagos: "111111111111111111111",
        FechaUltimoPago: "29102020",
        FormaPagoActual: "01",
        FrecuenciaPagos: "S",
        NombreOtorgante: "FINANCIERA",
        FechaCierreCuenta: "30102020",
        FechaUltimaCompra: "25092020",
        FechaActualizacion: "20072022",
        FechaAperturaCuenta: "25092020",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "1",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "20102020",
        FechaMasRecienteHistoricoPagos: "20062022",
        IdentificadorSociedadInformacionCrediticia: "1"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "R",
        SaldoActual: "0+",
        FechaReporte: "17072022",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "CC",
        CreditoMaximo: "80004",
        LimiteCredito: "197000",
        HistoricoPagos: "111111111111111111111111",
        FechaUltimoPago: "13072022",
        FormaPagoActual: "01",
        FrecuenciaPagos: "Z",
        MontoUltimoPago: "6290",
        NombreOtorgante: "BANCO",
        FechaUltimaCompra: "01072022",
        FechaActualizacion: "18072022",
        FechaAperturaCuenta: "30012009",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "17082016",
        FechaMasRecienteHistoricoPagos: "17062022",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "R",
        SaldoActual: "0+",
        FechaReporte: "14072022",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "CC",
        CreditoMaximo: "4210",
        LimiteCredito: "100000",
        HistoricoPagos: "1111111111111",
        FechaUltimoPago: "14072022",
        FormaPagoActual: "01",
        FrecuenciaPagos: "Z",
        MontoUltimoPago: "4210",
        NombreOtorgante: "BANCO",
        FechaUltimaCompra: "06062022",
        FechaActualizacion: "19072022",
        FechaAperturaCuenta: "07042021",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "14062021",
        FechaMasRecienteHistoricoPagos: "14062022",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "R",
        SaldoActual: "693+",
        FechaReporte: "07072022",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "CC",
        CreditoMaximo: "104316",
        LimiteCredito: "164500",
        HistoricoPagos: "1111111111111111111111UU",
        FechaUltimoPago: "05072022",
        FormaPagoActual: "01",
        FrecuenciaPagos: "Z",
        MontoUltimoPago: "693",
        NombreOtorgante: "BANCO",
        FechaUltimaCompra: "29062022",
        FechaActualizacion: "11072022",
        FechaAperturaCuenta: "15122017",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "07062017",
        MopHistoricoMorosidadMasGrave: "00",
        FechaMasRecienteHistoricoPagos: "07062022",
        FechaHistoricaMorosidadMasGrave: "31012018",
        ImporteSaldoMorosidadHistMasGrave: "0",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "4690",
        TipoCuenta: "R",
        SaldoActual: "38757+",
        FechaReporte: "01072022",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "CC",
        CreditoMaximo: "253990",
        LimiteCredito: "375000",
        HistoricoPagos: "111111111111111111X11111",
        FechaUltimoPago: "01072022",
        FormaPagoActual: "01",
        FrecuenciaPagos: "Z",
        MontoUltimoPago: "22706",
        NombreOtorgante: "BANCO",
        FechaUltimaCompra: "30062022",
        FechaActualizacion: "07072022",
        FechaAperturaCuenta: "02122019",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "01122018",
        FechaMasRecienteHistoricoPagos: "01062022",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "O",
        SaldoActual: "33941+",
        FechaReporte: "01072022",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "CC",
        CreditoMaximo: "283542",
        HistoricoPagos: "111111111111111111111111",
        FechaUltimoPago: "01072022",
        FormaPagoActual: "01",
        FrecuenciaPagos: "M",
        MontoUltimoPago: "50000",
        NombreOtorgante: "CIA Q' OTORGA",
        FechaUltimaCompra: "30062022",
        FechaActualizacion: "04072022",
        FechaAperturaCuenta: "29052019",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "01012018",
        FechaMasRecienteHistoricoPagos: "01062022",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "R",
        SaldoActual: "0+",
        FechaReporte: "30062022",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "CC",
        CreditoMaximo: "5863",
        LimiteCredito: "6000",
        HistoricoPagos: "UUU1U1U1",
        FechaUltimoPago: "18092008",
        FormaPagoActual: "UR",
        FrecuenciaPagos: "Z",
        MontoUltimoPago: "50",
        NombreOtorgante: "CIA Q' OTORGA",
        ClaveObservacion: "IA",
        FechaUltimaCompra: "22062006",
        FechaActualizacion: "01072022",
        FechaAperturaCuenta: "22032006",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "30102021",
        FechaMasRecienteHistoricoPagos: "30052022",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "R",
        SaldoActual: "0+",
        FechaReporte: "30062022",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "CC",
        CreditoMaximo: "0",
        LimiteCredito: "10000",
        HistoricoPagos: "UUUUUUUUUUUU111",
        FechaUltimoPago: "13052020",
        FormaPagoActual: "UR",
        FrecuenciaPagos: "Z",
        MontoUltimoPago: "0",
        NombreOtorgante: "FINANCIERA",
        FechaUltimaCompra: "13052020",
        FechaActualizacion: "08072022",
        FechaAperturaCuenta: "13052020",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "30032021",
        FechaMasRecienteHistoricoPagos: "30052022",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "311",
        TipoCuenta: "R",
        SaldoActual: "6383+",
        FechaReporte: "30062022",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "CC",
        CreditoMaximo: "9035",
        LimiteCredito: "16500",
        HistoricoPagos: "1111111111111111",
        FechaUltimoPago: "10062022",
        FormaPagoActual: "01",
        FrecuenciaPagos: "Z",
        MontoUltimoPago: "2951",
        NombreOtorgante: "FINANCIERA",
        FechaUltimaCompra: "29062022",
        FechaActualizacion: "09072022",
        FechaAperturaCuenta: "12022021",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "28022021",
        FechaMasRecienteHistoricoPagos: "30052022",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "R",
        SaldoActual: "0+",
        FechaReporte: "30062022",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "CC",
        CreditoMaximo: "552",
        LimiteCredito: "109000",
        HistoricoPagos: "111111111111X1XX1",
        FechaUltimoPago: "13012021",
        FormaPagoActual: "01",
        FrecuenciaPagos: "Z",
        MontoUltimoPago: "284",
        NombreOtorgante: "FINANCIERA",
        FechaUltimaCompra: "17122020",
        FechaActualizacion: "09072022",
        FechaAperturaCuenta: "14122020",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "30012021",
        FechaMasRecienteHistoricoPagos: "30052022",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "O",
        SaldoActual: "0+",
        FechaReporte: "30062022",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "MI",
        CreditoMaximo: "0",
        HistoricoPagos: "111111111111111111111111",
        FechaUltimoPago: "29062022",
        FormaPagoActual: "01",
        FrecuenciaPagos: "Z",
        MontoUltimoPago: "693",
        NombreOtorgante: "SERVICIOS",
        FechaUltimaCompra: "29062022",
        FechaActualizacion: "08072022",
        FechaAperturaCuenta: "29062018",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "30062018",
        FechaMasRecienteHistoricoPagos: "30052022",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "2198",
        TipoCuenta: "M",
        NumeroPagos: "360",
        SaldoActual: "319816+",
        FechaReporte: "30062022",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "RE",
        CreditoMaximo: "403901",
        LimiteCredito: "403901",
        HistoricoPagos: "111111111111111111111111",
        FechaUltimoPago: "07052022",
        FormaPagoActual: "01",
        FrecuenciaPagos: "M",
        MontoUltimoPago: "4011",
        NombreOtorgante: "HIPOTECAGOBIERNO",
        FechaUltimaCompra: "21072017",
        FechaActualizacion: "08072022",
        FechaAperturaCuenta: "21072017",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "30082017",
        FechaMasRecienteHistoricoPagos: "30052022",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        Garantia: "AMORES 1035 102 CP 03100",
        MontoPagar: "26988",
        TipoCuenta: "M",
        NumeroPagos: "240",
        SaldoActual: "1304746+",
        FechaReporte: "30062022",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "RE",
        CreditoMaximo: "3555000",
        LimiteCredito: "0",
        HistoricoPagos: "111111111111111111111111",
        FechaUltimoPago: "17062022",
        FormaPagoActual: "01",
        FrecuenciaPagos: "M",
        MontoUltimoPago: "26995",
        NombreOtorgante: "BANCO",
        FechaUltimaCompra: "30062017",
        FechaActualizacion: "09072022",
        FechaAperturaCuenta: "30062017",
        ClaveUnidadMonetaria: "MX",
        ValorActivoValuacion: "4595000",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "30062017",
        MopHistoricoMorosidadMasGrave: "00",
        FechaMasRecienteHistoricoPagos: "30052022",
        FechaHistoricaMorosidadMasGrave: "30062017",
        ImporteSaldoMorosidadHistMasGrave: "0",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        Garantia: "BIEN INMUEBLE",
        MontoPagar: "7937",
        TipoCuenta: "R",
        NumeroPagos: "40",
        SaldoActual: "23311+",
        FechaReporte: "30062022",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "ST",
        CreditoMaximo: "354913",
        LimiteCredito: "354913",
        HistoricoPagos: "111111111111111111111111",
        FechaUltimoPago: "11052022",
        FormaPagoActual: "01",
        FrecuenciaPagos: "Z",
        MontoUltimoPago: "7970",
        NombreOtorgante: "FONDOS Y FIDEIC",
        FechaUltimaCompra: "02042012",
        FechaActualizacion: "07072022",
        FechaAperturaCuenta: "05082010",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "30082016",
        FechaMasRecienteHistoricoPagos: "30052022",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "O",
        SaldoActual: "0+",
        FechaReporte: "30062022",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "CL",
        CreditoMaximo: "5769",
        LimiteCredito: "20000",
        HistoricoPagos: "111111111111111111111111",
        FechaUltimoPago: "23062022",
        FormaPagoActual: "01",
        FrecuenciaPagos: "M",
        MontoUltimoPago: "1031",
        NombreOtorgante: "COMUNICACIONES",
        FechaUltimaCompra: "22062022",
        FechaActualizacion: "07072022",
        FechaAperturaCuenta: "17062011",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "31082016",
        FechaMasRecienteHistoricoPagos: "24052022",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "1490",
        TipoCuenta: "R",
        SaldoActual: "1963+",
        FechaReporte: "30062022",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "CC",
        CreditoMaximo: "66590",
        LimiteCredito: "119000",
        HistoricoPagos: "111111111111111111111111",
        FechaUltimoPago: "20062022",
        FormaPagoActual: "01",
        FrecuenciaPagos: "Z",
        MontoUltimoPago: "6404",
        NombreOtorgante: "BANCO",
        FechaUltimaCompra: "23062022",
        FechaActualizacion: "07072022",
        FechaAperturaCuenta: "01012006",
        ClaveUnidadMonetaria: "MX",
        TotalPagosReportados: "029",
        UltimaFechaSaldoCero: "01012006",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "21072016",
        FechaMasRecienteHistoricoPagos: "21052022",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "I",
        NumeroPagos: "4",
        SaldoActual: "0+",
        FechaReporte: "30062022",
        SaldoVencido: "0",
        TipoContrato: "AF",
        CreditoMaximo: "2400",
        LimiteCredito: "2400",
        HistoricoPagos: "1UUU1UU",
        FechaUltimoPago: "16122021",
        FormaPagoActual: "01",
        FrecuenciaPagos: "S",
        NombreOtorgante: "FINANCIERA",
        FechaUltimaCompra: "15102021",
        FechaActualizacion: "30062022",
        FechaAperturaCuenta: "15102021",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "1",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "30112021",
        FechaMasRecienteHistoricoPagos: "30052022",
        IdentificadorSociedadInformacionCrediticia: "1"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "R",
        SaldoActual: "0+",
        FechaReporte: "26062022",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "CL",
        CreditoMaximo: "27965",
        LimiteCredito: "116000",
        HistoricoPagos: "111111111111111111111111",
        FechaUltimoPago: "26062022",
        FormaPagoActual: "01",
        FrecuenciaPagos: "Z",
        MontoUltimoPago: "1",
        NombreOtorgante: "TIENDA COMERCIAL",
        FechaUltimaCompra: "31032019",
        FechaActualizacion: "29062022",
        FechaAperturaCuenta: "23112006",
        ClaveUnidadMonetaria: "MX",
        UltimaFechaSaldoCero: "26032008",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "26082016",
        FechaMasRecienteHistoricoPagos: "26052022",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "I",
        NumeroPagos: "3",
        SaldoActual: "0+",
        FechaReporte: "28022022",
        SaldoVencido: "0",
        TipoContrato: "PL",
        CreditoMaximo: "119",
        LimiteCredito: "119",
        FechaUltimoPago: "14022022",
        FormaPagoActual: "01",
        FrecuenciaPagos: "S",
        NombreOtorgante: "SERVICIOS",
        FechaCierreCuenta: "14022022",
        FechaUltimaCompra: "03012022",
        FechaActualizacion: "28022022",
        FechaAperturaCuenta: "03012022",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "1",
        IndicadorTipoResponsabilidad: "I",
        IdentificadorSociedadInformacionCrediticia: "1"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "I",
        NumeroPagos: "96",
        SaldoActual: "0+",
        FechaReporte: "26102021",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "AU",
        CreditoMaximo: "314500",
        LimiteCredito: "0",
        HistoricoPagos: "111111111111111111111",
        FechaUltimoPago: "26102021",
        FormaPagoActual: "01",
        FrecuenciaPagos: "S",
        MontoUltimoPago: "3651",
        NombreOtorgante: "BANCO",
        ClaveObservacion: "CC",
        FechaCierreCuenta: "26102021",
        FechaUltimaCompra: "31122019",
        FechaActualizacion: "02112021",
        FechaAperturaCuenta: "31122019",
        ClaveUnidadMonetaria: "MX",
        ValorActivoValuacion: "564500",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "15012020",
        FechaMasRecienteHistoricoPagos: "15092021",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "R",
        SaldoActual: "0+",
        FechaReporte: "30092021",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "CC",
        CreditoMaximo: "5863",
        LimiteCredito: "6000",
        FechaUltimoPago: "18092008",
        FormaPagoActual: "01",
        FrecuenciaPagos: "Z",
        MontoUltimoPago: "50",
        NombreOtorgante: "BANCO",
        ClaveObservacion: "CA",
        FechaCierreCuenta: "30092021",
        FechaUltimaCompra: "22062006",
        FechaActualizacion: "28012022",
        FechaAperturaCuenta: "22032006",
        ClaveUnidadMonetaria: "MX",
        TotalPagosReportados: "022",
        UltimaFechaSaldoCero: "14092007",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "O",
        SaldoActual: "0+",
        FechaReporte: "28022021",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "PS",
        CreditoMaximo: "0",
        HistoricoPagos: "111",
        FechaUltimoPago: "27012021",
        FormaPagoActual: "01",
        FrecuenciaPagos: "M",
        MontoUltimoPago: "754",
        NombreOtorgante: "SERVICIOS",
        ClaveObservacion: "CC",
        FechaCierreCuenta: "02022021",
        FechaUltimaCompra: "02022021",
        FechaActualizacion: "10032021",
        FechaAperturaCuenta: "20112020",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "28112020",
        FechaMasRecienteHistoricoPagos: "28012021",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "3703",
        TipoCuenta: "I",
        NumeroPagos: "96",
        SaldoActual: "314500+",
        FechaReporte: "31122019",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "AU",
        CreditoMaximo: "314500",
        LimiteCredito: "314500",
        FormaPagoActual: "01",
        FrecuenciaPagos: "K",
        MontoUltimoPago: "0",
        NombreOtorgante: "BANCO",
        FechaUltimaCompra: "18122019",
        FechaActualizacion: "06012020",
        FechaAperturaCuenta: "18122019",
        ClaveUnidadMonetaria: "MX",
        ValorActivoValuacion: "564500",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "R",
        SaldoActual: "0+",
        FechaReporte: "30112019",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "CC",
        CreditoMaximo: "75900",
        LimiteCredito: "75900",
        HistoricoPagos: "1111111111",
        FormaPagoActual: "01",
        FrecuenciaPagos: "Z",
        MontoUltimoPago: "0",
        NombreOtorgante: "BANCO",
        ClaveObservacion: "CC",
        FechaCierreCuenta: "25112019",
        FechaActualizacion: "10122019",
        FechaAperturaCuenta: "16112018",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "30012019",
        FechaMasRecienteHistoricoPagos: "30102019",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "O",
        SaldoActual: "0+",
        FechaReporte: "31102019",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "CC",
        CreditoMaximo: "175006",
        HistoricoPagos: "111111111111111111111111",
        FechaUltimoPago: "25102019",
        FormaPagoActual: "01",
        FrecuenciaPagos: "M",
        MontoUltimoPago: "4365",
        NombreOtorgante: "CIA Q' OTORGA",
        ClaveObservacion: "CC",
        FechaCierreCuenta: "31102019",
        FechaUltimaCompra: "22102019",
        FechaActualizacion: "07112019",
        FechaAperturaCuenta: "13092012",
        ClaveUnidadMonetaria: "MX",
        TotalPagosReportados: "041",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "31082016",
        FechaMasRecienteHistoricoPagos: "21092019",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "I",
        NumeroPagos: "143",
        SaldoActual: "0+",
        FechaReporte: "30042019",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "PN",
        CreditoMaximo: "52415",
        LimiteCredito: "0",
        HistoricoPagos: "1111111111111111110",
        FechaUltimoPago: "04042019",
        FormaPagoActual: "01",
        FrecuenciaPagos: "S",
        MontoUltimoPago: "48516",
        NombreOtorgante: "BANCO",
        ClaveObservacion: "CC",
        FechaCierreCuenta: "04042019",
        FechaUltimaCompra: "24052018",
        FechaActualizacion: "07052019",
        FechaAperturaCuenta: "24052018",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "04092017",
        MopHistoricoMorosidadMasGrave: "00",
        FechaMasRecienteHistoricoPagos: "04032019",
        FechaHistoricaMorosidadMasGrave: "31052018",
        ImporteSaldoMorosidadHistMasGrave: "0",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "I",
        NumeroPagos: "36",
        SaldoActual: "0+",
        FechaReporte: "23122018",
        ModoReportar: "A",
        SaldoVencido: "0",
        TipoContrato: "AU",
        CreditoMaximo: "181706",
        LimiteCredito: "181706",
        HistoricoPagos: "111111111111111111111111",
        FechaUltimoPago: "18122018",
        FormaPagoActual: "01",
        FrecuenciaPagos: "M",
        MontoUltimoPago: "4765",
        NombreOtorgante: "AUTOMOTRIZ",
        FechaCierreCuenta: "18122018",
        FechaUltimaCompra: "16122015",
        FechaActualizacion: "26122018",
        FechaAperturaCuenta: "16122015",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "0",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "31082016",
        FechaMasRecienteHistoricoPagos: "23112018",
        IdentificadorSociedadInformacionCrediticia: "0"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "O",
        NumeroPagos: "28",
        SaldoActual: "0+",
        FechaReporte: "31082018",
        SaldoVencido: "0",
        TipoContrato: "MI",
        CreditoMaximo: "2300",
        LimiteCredito: "0",
        HistoricoPagos: "U1111UUUUUUUUUUUUU1U11",
        FechaUltimoPago: "31072018",
        FormaPagoActual: "01",
        FrecuenciaPagos: "M",
        NombreOtorgante: "COMUNICACIONES",
        ClaveObservacion: "CC",
        FechaCierreCuenta: "31072018",
        FechaUltimaCompra: "27072018",
        FechaActualizacion: "31082018",
        FechaAperturaCuenta: "12042016",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "1",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "31102016",
        FechaMasRecienteHistoricoPagos: "31072018",
        IdentificadorSociedadInformacionCrediticia: "1"
      },
      {
        MontoPagar: "0",
        TipoCuenta: "O",
        NumeroPagos: "7",
        SaldoActual: "0+",
        FechaReporte: "31082018",
        SaldoVencido: "0",
        TipoContrato: "MI",
        CreditoMaximo: "2274",
        LimiteCredito: "0",
        HistoricoPagos: "U1111",
        FechaUltimoPago: "30082018",
        FormaPagoActual: "01",
        FrecuenciaPagos: "M",
        NombreOtorgante: "COMUNICACIONES",
        ClaveObservacion: "CC",
        FechaCierreCuenta: "30082018",
        FechaUltimaCompra: "27082018",
        FechaActualizacion: "31082018",
        FechaAperturaCuenta: "31012018",
        ClaveUnidadMonetaria: "MX",
        NumeroTelefonoOtorgante: "1",
        IndicadorTipoResponsabilidad: "I",
        FechaMasAntiguaHistoricoPagos: "31032018",
        FechaMasRecienteHistoricoPagos: "31072018",
        IdentificadorSociedadInformacionCrediticia: "1"
      }
    ]
  },
  Empleos: {
    Empleo: [
      {
        CP: "11910",
        Cargo: "14",
        Ciudad: "CD DE MEXICO",
        Estado: "CDMX",
        CodPais: "MX",
        Direccion1: "C MTS URALES 430 424",
        NombreEmpresa: "EOS SOOFTWARE",
        NumeroTelefono: "5611225094",
        ColoniaPoblacion: "LOMAS DE BEZARES",
        FechaReportoEmpleo: "27042022",
        DelegacionMunicipio: "MIGUEL HIDALGO"
      },
      {
        CP: "42630",
        Estado: "HGO",
        CodPais: "MX",
        Direccion1: "AV DILIGENCIAS SN",
        NombreEmpresa: "EDUARDO BENITEZ GASPAR",
        NumeroTelefono: "7711532248",
        ColoniaPoblacion: "PATRIA NVA",
        DelegacionMunicipio: "SANTIAGO DE ANAYA"
      }
    ]
  },
  Domicilios: {
    Domicilio: [
      {
        CP: "42082",
        Ciudad: "PACHUCA DE SOTO",
        Estado: "HGO",
        CodPais: "MX",
        Direccion1: "CALLE FALSA 23",
        ColoniaPoblacion: "PRIVADAS DE LA HERRADURA",
        FechaReporteDireccion: "11032022"
      },
      {
        CP: "42082",
        Ciudad: "PACHUCA DE SOTO",
        Estado: "HGO",
        CodPais: "MX",
        Direccion1: "CALLE FALSA 13",
        ColoniaPoblacion: "LOS GIRASOLES",
        FechaReporteDireccion: "11032022"
      },
      {
        CP: "42082",
        Ciudad: "PACHUCA DE SOTO",
        Estado: "HGO",
        CodPais: "MX",
        Direccion1: "CALLE FALSA 123",
        ColoniaPoblacion: "VILLAREAL",
        FechaReporteDireccion: "17112021"
      },
      {
        CP: "42082",
        Ciudad: "PACHUCA DE SOTO",
        Estado: "HGO",
        CodPais: "MX",
        Direccion1: "CALLE 32 32",
        ColoniaPoblacion: "PARQUE ESMERALDA",
        FechaReporteDireccion: "08102021"
      }
    ]
  },
  Encabezado: {
    ClavePais: "MX",
    ClaveOtorgante: "FFA8841002",
    IdentificadorBuro: "1010",
    NumeroControlConsulta: "2567162717",
    NumeroReferenciaOperador: "",
    ClaveRetornoConsumidorPrincipal: "1",
    ClaveRetornoConsumidorSecundario: "0"
  },
  HawkAlertBD: {
    HawkAlertBD: [
      {
        Mensaje: "TELEFONO 7711532248 CORRESPONDE A NUMERO FIJO",
        CodigoClave: "860",
        FechaReporte: "30052022",
        TipoInstitucion: "BURO DE CREDITO"
      },
      {
        Mensaje: "TELEFONO 5611225094 NO CORRESPONDE A ZONA POSTAL",
        CodigoClave: "850",
        FechaReporte: "30052022",
        TipoInstitucion: "BURO DE CREDITO"
      },
      {
        Mensaje: "TELEFONO 7711532248 NO CORRESPONDE A ZONA POSTAL",
        CodigoClave: "850",
        FechaReporte: "30052022",
        TipoInstitucion: "BURO DE CREDITO"
      }
    ]
  },
  ResumenReporte: {
    ResumenReporte: [
      {
        NumeroMOP0: "00",
        NumeroMOP1: "03",
        NumeroMOP2: "00",
        NumeroMOP3: "00",
        NumeroMOP4: "00",
        NumeroMOP5: "00",
        NumeroMOP6: "00",
        NumeroMOP7: "00",
        TipoMoneda: "MX",
        NumeroMOP96: "00",
        NumeroMOP97: "00",
        NumeroMOP99: "00",
        NumeroMOPUR: "00",
        NumeroCuentas: "0003",
        CuentasDisputa: "00",
        FechaIngresoBD: "07092017",
        MensajesAlerta: "NNYNY",
        CuentasCerradas: "0001",
        TotalPagosPagosFijos: "000000000",
        TotalPagosRevolventes: "000000000",
        TotalSolicitudesReporte: "39",
        CuentasNegativasActuales: "0000",
        CuentasPagosFijosHipotecas: "0000",
        CuentasRevolventesAbiertas: "0003",
        CuentasClavesHistoriaNegativa: "0001",
        FechaAperturaCuentaMasAntigua: "27032018",
        TotalSaldosActualesPagosFijos: "000000000+",
        TotalSaldosVencidosPagosFijos: "000000000",
        FechaAperturaCuentaMasReciente: "16012021",
        NumeroSolicitudesUltimos6Meses: "09",
        TotalCreditosMaximosPagosFijos: "000000000",
        TotalLimitesCreditoRevolventes: "000005000",
        TotalSaldosActualesRevolventes: "000000500+",
        TotalSaldosVencidosRevolventes: "000000500",
        TotalCreditosMaximosRevolventes: "000005714",
        FechaSolicitudReporteMasReciente: "30052022",
        ExistenciaDeclaracionesConsumidor: "N",
        NumeroTotalCuentasDespachoCobranza: "00",
        NuevaDireccionReportadaUltimos60Dias: "N",
        PctLimiteCreditoUtilizadoRevolventes: "000",
        NumeroTotalSolicitudesDespachosCobranza: "00",
        FechaSolicitudMasRecienteDespachoCobranza: "00000000",
        FechaAperturaCuentaMasRecienteDespachoCobranza: "00000000"
      }
    ]
  },
  ScoreBuroCredito: {
    ScoreBC: [
      {
        ValorScore: "0692",
        CodigoRazon: ["32", "21"],
        CodigoScore: "007",
        nombreScore: "BC SCORE"
      }
    ]
  },
  HawkAlertConsulta: {
    HawkAlertC: [
      {
        Mensaje: "NO EXISTE INFORMACION",
        CodigoClave: "002",
        FechaReporte: "30052022",
        TipoInstitucion: "BURO DE CREDITO"
      }
    ]
  },
  ConsultasEfectuadas: {
    ConsultaEfectuada: [
      {
        TipoContrato: "PL",
        FechaConsulta: "30052022",
        ResultadoFinal: "1",
        ImporteContrato: "000000000",
        NombreOtorgante: "BURO DE CREDITO",
        TelefonoOtorgante: "54494832",
        IdentificacionBuro: "0000",
        ClaveUnidadMonetaria: "MX",
        IdentificadorOrigenConsulta: "1"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "30052022",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "AU",
        FechaConsulta: "27042022",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "AUTOMOTRIZ",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CC",
        FechaConsulta: "09042022",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "COMUNICACIONES",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CC",
        FechaConsulta: "12032022",
        ResultadoFinal: "1",
        ImporteContrato: "000000000",
        NombreOtorgante: "BURO DE CREDITO",
        IdentificacionBuro: "0000",
        ClaveUnidadMonetaria: "MX",
        IdentificadorOrigenConsulta: "1"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "12032022",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CC",
        FechaConsulta: "11032022",
        ResultadoFinal: "1",
        ImporteContrato: "000000000",
        NombreOtorgante: "BURO DE CREDITO",
        IdentificacionBuro: "0000",
        ClaveUnidadMonetaria: "MX",
        IdentificadorOrigenConsulta: "1"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "11032022",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CC",
        FechaConsulta: "02032022",
        ResultadoFinal: "1",
        ImporteContrato: "000000000",
        NombreOtorgante: "BURO DE CREDITO",
        IdentificacionBuro: "0000",
        ClaveUnidadMonetaria: "MX",
        IdentificadorOrigenConsulta: "1"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "02032022",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CC",
        FechaConsulta: "26112021",
        ResultadoFinal: "1",
        ImporteContrato: "000000000",
        NombreOtorgante: "BURO DE CREDITO",
        IdentificacionBuro: "0000",
        ClaveUnidadMonetaria: "MX",
        IdentificadorOrigenConsulta: "1"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "26112021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "19112021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "17112021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "25102021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "21102021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "08102021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "04102021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "29092021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "28092021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "27092021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "24092021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "22092021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "21092021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "20092021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "17092021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "15092021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "14092021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "13092021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "10092021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "02092021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "01092021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "30072021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CS",
        FechaConsulta: "29072021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CC",
        FechaConsulta: "21072021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CC",
        FechaConsulta: "20072021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CC",
        FechaConsulta: "18072021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CC",
        FechaConsulta: "17072021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CC",
        FechaConsulta: "08072021",
        ClaveOtorgante: "FFA8841002",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "EOS",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      },
      {
        TipoContrato: "CC",
        FechaConsulta: "16012021",
        ResultadoFinal: "0",
        ImporteContrato: "0",
        NombreOtorgante: "COMUNICACIONES",
        IdentificadorOrigenConsulta: "0",
        IndicadorTipoResponsabilidad: "I"
      }
    ]
  }
};
